apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: message
      description: the message
  tasks:
    - name: pipeline-pwd-twst
      runAfter: [pipeline-read-task]
      taskRef:
        name: pwd-task-20
       