apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: read-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc
  steps:
    - name: message-mount-read
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - ls -la /step-mount;
          cat /step-mount/message;
      volumeMounts:
        - mountPath: /step-mount
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)